### PR TITLE
fix solr cloud upload and ansible lint warnings

### PR DESCRIPTION
**Pull request by psachs**
set SOLR_ENV to solr_insh_default for cloud upload task to enforce solr command to use the correct solr environment

fix lint warnings due to capitalized true and false

### CODE REVIEW

**Comment by psachs** [comment]
The build fails, due to a wrong regex in the java role. Apparently the second time `java_major_version|string` is used right before  the URL part `/GPL/openjdk-` in `openjdk-fallback.yml` the download URL has the build number in it and not the java major version.
Therefor the correct download URL is not found by the regex and the build job fails. I am not sure how you want to solve that for testing

**Comment by pavelpikta** [comment]
> The build fails, due to a wrong regex in the java role. Apparently the second time `java_major_version|string` is used right before the URL part `/GPL/openjdk-` in `openjdk-fallback.yml` the download URL has the build number in it and not the java major version.
> Therefor the correct download URL is not found by the regex and the build job fails. I am not sure how you want to solve that for testing

Thanks for contribution. Yes, we know about  issue with openjdk url.  Issue fixed in this pr https://github.com/lean-delivery/ansible-role-java/pull/83.
Please wait new java role release.

**Comment by pavelpikta** [comment]
@psachs java role is fixed

**Comment by psachs** [comment]
@pavelpikta thanks for the update, now the CI passes again. Merge request should therefore be ready for review

**Review by ViachaslauKabak — APPROVED** [review]

**Pull request merged**
